
#ifndef _Q_DEFS_H_
#define _Q_DEFS_H_

typedef enum{
	Q_CLIENT_OK,
	Q_CLIENT_UNABLE_TO_START,
	Q_CLIENT_UNABLE_TO_STOP,
	Q_CLIENT_NTW_IFACES_UNINITIALISED,
	Q_CLIENT_UNABLE_TO_CREATE_CON,
	Q_CLIENT_UNABLE_TO_BIND,
	Q_CLIENT_PACKET_RECV_ERR
}Q_client_err_e;


#endif
